import React from "react";

const PrivacyPolicy = () => {
  return (
    <div className="p-6 bg-gray-100 text-gray-800">
      <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
      <p className="mb-4 text-sm text-gray-500">Last Updated: December 3, 2024</p>
      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">Information We Collect</h2>
        <p>
          Our site does not automatically collect personal information. However, we may log non-identifiable data, such as
          usage statistics, to improve the service.
        </p>
      </section>
      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">Data Usage</h2>
        <p>
          The UUIDs generated are created locally in your browser and are not stored or transmitted to our servers. We do not
          collect or track the UUIDs generated by users.
        </p>
      </section>
      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">Cookies</h2>
        <p>
          We may use cookies to enhance user experience, such as remembering preferences or tracking aggregated usage
          statistics. You can disable cookies in your browser settings at any time.
        </p>
      </section>
      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">Data Sharing</h2>
        <p>We do not share any information with third parties unless required by law.</p>
      </section>
      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">Security</h2>
        <p>
          We implement technical measures to safeguard our systems and ensure secure interactions with our site. However, no
          method is entirely infallible, so we advise caution when sharing information online.
        </p>
      </section>
      <section>
        <h2 className="text-xl font-semibold mb-2">Policy Changes</h2>
        <p>
          We may update this Privacy Policy from time to time. Significant changes will be communicated on our site. We
          recommend reviewing this page regularly.
        </p>
      </section>
    </div>
  );
};

export default PrivacyPolicy;
